# -*- coding: utf-8 -*-
"""ejercicio1

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1yalW341AnfRATmjA0Vwyxf0pB4ybZsVp
"""

# Autor: Reyna Yazmin Ríos Martínez
# Fecha: 19 / Oct / 2023
# Descripción: Histograma R1


def barra(calif):
    print('*' * calif)


def histograma(asignatura, calificaciones):
    print(asignatura + " histograma")
    for calif in calificaciones:
        barra(calif)


calificaciones_asignatura = {
    "Redes WAN": [10],
    "Programación de Redes": [8],
    "Servidores": [9],
    "Probabilidad y Estadistica":[9],
    "Electronica para IdC":[9],
    "Formación Sociocultural":[10],
    "Inglés":[8]
}


for asignatura, calificaciones in calificaciones_asignatura.items():
    histograma(asignatura, calificaciones)