# -*- coding: utf-8 -*-
"""parse_json01

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1ktjtO-nw5nXAx66exU2CzwJW9XF0KX8z
"""

'''
  Nombre: Reyna Yazmin Ríos Martínez
  Fecha: 23 / Oct /2023
  Descripción: Imporatando API
'''

import urllib.parse
import requests

main_api = "https://www.mapquestapi.com/directions/v2/route?"
orig = "Dolores Hidalgo"
dest = "Guanajuato"
key = "YW0ScRakZg1x3d8xSLUvJlD7by2jQEW9"

url = main_api + urllib.parse.urlencode({"key": key, "from":orig, "to":dest})
json_data = requests.get(url).json()
print(json_data['route']['sessionId'])

#Extraer la distancia y el tiempo
print(json_data['route']['distance'])
print(json_data['route']['time'])

#Extraer del primer elemento Legs el campo formattedTime
print(json_data['route']['formattedTime'])